#***************************************************************************#
# ALGORÍTMICA
# 
# Autores:
# 	Hossam El Amraoui Leghzali
# 	Javier Montaño Rubio
# 	Raúl Granados López
# 
# Práctica 2
# 
# Fichero: makefile
# 
#***************************************************************************#

all: Practica2_exe

Practica2_exe: Practica2.cpp
	@echo Creando $@
	@g++ $< -o $@

clean:
	@echo Borrando ejecutables
	@rm -rf *_exe
